### ISSUE TITLE
Mising method?

### ISSUE THREAD

**Issue by nickocreates** [PhantomBadger/JumpKing-TwitchRavens#9]
Not sure what I did wrong, installed according to instructions but get this error as soon as I get in game 

ERR - Error on Post-GameLoop Init: System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<EntityComponent.Entity> EntityComponent.EntityManager.get_Entities()'.
   at JumpKingRavensMod.Entities.Raven.RavenLandingPositionsCache..ctor(ILogger newLogger)
   at JumpKingRavensMod.Entities.MessengerRavenSpawningEntity..ctor(UserSettings userSettings, ModEntityManager modEntityManager, List`1 messengerRavenTriggers, Boolean isGameLoopRunning, ILogger logger) in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingRavensMod\Entities\MessengerRavenSpawningEntity.cs:line 56
   at JumpKingRavensMod.JumpKingRavensModEntry.<>c__DisplayClass1_0.<Init>b__0() in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingRavensMod\JumpKingRavensModEntry.cs:line 230

**Comment by samcarsonx** [comment]
The mod is broken on the latest version, but you can use legacy versions to get it working. Right click the game in Steam -> properties -> betas -> select legacy. Fully uninstall (delete the installation folder after uninstalling within Steam as some files are left behind) then reinstall again

**Comment by PhantomBadger** [comment]
We're looking to port the mod to the workshop in the coming week or two :)
